/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
    	System.out.println(args.length);
   		MyDate fromDate = MyDate.of(args[0]);
   		MyDate toDate = MyDate.of(args[1]);
   		// subtract one here because our epochDays calculation includes the end day
   		// which makes sense for an epoch calculation but isn't the spec for this test
   		System.out.println(Math.abs(toDate.minus(fromDate).getEpochDays() - 1));
    }
}
